# Generated by Django 4.1.7 on 2023-03-30 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=100, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['FIO'],
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название книги')),
                ('genre', models.DateField(verbose_name='Жанр')),
                ('write_date', models.DateField(verbose_name='Год написания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.authors', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='Тираж')),
                ('date', models.DateField(verbose_name='Дата')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.books', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название издательства')),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_for_one', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена одной книги')),
                ('total_price_for_all', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость проданных книг')),
                ('count', models.IntegerField(default=0, verbose_name='Количество проданных книг')),
                ('date', models.DateField(verbose_name='Дата')),
                ('publications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.publications', verbose_name='Публикации')),
            ],
            options={
                'verbose_name': 'Годовая продажа',
                'verbose_name_plural': 'Годовые продажи',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='publications',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.publishers', verbose_name='Издательство'),
        ),
    ]
