# Generated by Django 4.1.7 on 2023-03-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(max_length=60, verbose_name='Жанр'),
        ),
    ]
