# Generated by Django 4.1.4 on 2023-04-01 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_sales_price_for_one_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='publications',
            new_name='publication',
        ),
    ]
