# Generated by Django 4.1.4 on 2023-04-01 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_publications_sales_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='publication',
            new_name='publications',
        ),
    ]
