# Generated by Django 4.1.4 on 2023-04-01 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_publication_sales_publications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='birth_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='books',
            name='write_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Год написания'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
    ]
