# Generated by Django 4.1.7 on 2023-03-29 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название магазина')),
                ('address', models.CharField(max_length=90, verbose_name='Адрес магазина')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Эл.почта')),
                ('created_date', models.DateField(auto_now=True, verbose_name='Дата основания')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.store', verbose_name='Id магазина')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
